name = "ai-test-case-creator-agent"
main = "index.js"
compatibility_date = "2025-04-25"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "SECRET_STORE"
id = "2a3cf21a3ebb4152a19cd28c93838075"
